/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#121414",
        "surface-dim": "#121414",
        "surface-bright": "#37393a",
        "surface-container-lowest": "#0c0f0f",
        "surface-container-low": "#1a1c1c",
        "surface-container": "#1e2020",
        "surface-container-high": "#282a2b",
        "surface-container-highest": "#333535",
        "on-surface": "#e2e2e2",
        "on-surface-variant": "#e4beb9",
        "inverse-surface": "#e2e2e2",
        "inverse-on-surface": "#2f3131",
        "outline": "#ab8985",
        "outline-variant": "#5b403d",
        "surface-tint": "#ffb4ac",
        "primary": "#ffb4ac",
        "on-primary": "#690006",
        "primary-container": "#ff544c",
        "on-primary-container": "#5c0005",
        "inverse-primary": "#bb171c",
        "secondary": "#b8c9d3",
        "on-secondary": "#23333a",
        "secondary-container": "#3b4b53",
        "on-secondary-container": "#aabbc5",
        "tertiary": "#c8c6c5",
        "on-tertiary": "#313030",
        "tertiary-container": "#929090",
        "on-tertiary-container": "#2a2a29",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffdad6",
        "primary-fixed-dim": "#ffb4ac",
        "on-primary-fixed": "#410002",
        "on-primary-fixed-variant": "#93000d",
        "secondary-fixed": "#d4e5ef",
        "secondary-fixed-dim": "#b8c9d3",
        "on-secondary-fixed": "#0d1e25",
        "on-secondary-fixed-variant": "#394951",
        "tertiary-fixed": "#e5e2e1",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed": "#1c1b1b",
        "on-tertiary-fixed-variant": "#474646",
        "background": "#121414",
        "on-background": "#e2e2e2",
        "surface-variant": "#333535",
        "ivk-red": "#ff544c",
        "ivk-glow": "rgba(255, 84, 76, 0.4)",
        "ivk-black": "#121414"
      },
      boxShadow: {
        'glow': '0 0 20px 2px rgba(255, 84, 76, 0.4)',
        'glow-strong': '0 0 30px 5px rgba(255, 84, 76, 0.6)',
        'glow-sm': '0 0 10px 1px rgba(255, 84, 76, 0.3)',
        'inner-glow': 'inset 0 0 15px rgba(255, 84, 76, 0.2)',
      },
      backgroundImage: {
        'gradient-ivk': 'linear-gradient(135deg, #ff544c 0%, #93000a 100%)',
        'gradient-dark': 'linear-gradient(180deg, #1e2020 0%, #121414 100%)',
        'gradient-card': 'linear-gradient(145deg, #282a2b 0%, #1a1c1c 100%)',
      },
      borderRadius: {
        "sm": "0.125rem",
        "DEFAULT": "0.25rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "xs": "4px",
        "sm": "12px",
        "md": "20px",
        "lg": "32px",
        "xl": "48px",
        "gutter": "16px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "display-lg": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "label-technical": ["JetBrains Mono", "monospace"],
        "label-sm": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "34px", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-technical": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      },
      screens: {
        'xs': '480px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },
    },
  },
  plugins: [],
}
